### ISSUE TITLE
Div "image-center-outer" goes over left sub-menu, navigation not possible.

### ISSUE THREAD

**Issue by webian** [benjaminkott/bootstrap_package#113]
Hi @benjaminkott!

Let's suppose that we have a page that begins with an image positioned "Above, center" or "Below, center".
If this page has a layout with left sub-menu, the div "image-center-outer" goes over the sub-menu so it's impossible to click its links. This is because the div "image-center-outer" is left floated.

I'm sure that you did choose this approach to center the image for some good reason so I prefer to wait for your feedback before write a patch to fix this.

**Comment by Hydroxi** [comment]
Just stumbled on the same bug. Got any fix yet?

**Comment by webian** [comment]
Hi @Hydroxi,
waiting for an answer from @benjaminkott, I temporary fixed this with this css code:

    .image-center-outer { float: none; }

**Comment by Hydroxi** [comment]
Aww so simple. Thanks man.

**Comment by timofo** [comment]
maybe this has something to do with my new issue: "1 image column"
Please take a look into it.
I had the same problem that the images go over a right submenu. because of the float:left;
But the float:left is not the real problem. The problem is that the div with "image-column" doesnt get the class "col-md-12". If it get it. Then the float:left doesnt affect the images in a wrong way.

**Comment by Gorli** [comment]
.image-center {
overflow: hidden;
}

I have recommended:
https://github.com/benjaminkott/bootstrap_package/issues/159

**Comment by benjaminkott** [comment]
Hey guys, problem should be solved now - let me know when there is still an issue.
