### ISSUE TITLE
Grids / HTML for EXT:container

### ISSUE THREAD

**Issue by SventB** [benjaminkott/bootstrap_package#1225]
Thank you for adding configuration for EXT:container.

But why implementing your own SCSS (in _contentcontainer.scss) instead of using Bootstrap grid HTML/CSS (https://getbootstrap.com/docs/5.1/layout/grid/)?

**Comment by benjaminkott** [comment]
Hey, I don`t see a need to use grid classes from bootstrap, they are way more complex to setup and are breaking when bootstrap decides to make updates in the future. The simple CSS is easy to override from a users perspective and must not be changed or adapted on future releases.

Since we from time to time had multiple versions of bootstrap supported - this seems to be the best way to avoid breaking customizing from the users.

**Comment by SventB** [comment]
Ok, thanks for clarifying.
