### ISSUE TITLE
Perfomance issue of clearCacheCmd = all

### ISSUE THREAD

**Issue by jvanderkroon** [benjaminkott/bootstrap_package#126]
In the file Configuration/PageTS/TCEMAIN.txt stays the option: clearCacheCmd = all

This configuration results in a clearcache command for every record. This results in a bad performance on the complete website when there is backend user that makes changes in the site.

Can you remove the clearCacheCmd.

**Comment by khaefeli** [comment]
+1 

it also slows down the backend for editors, when they saving a content element:
with clearcache = ~1200ms
without clearcache = ~500ms

it's important to focus on performance, because the bootstrap package is used by the introduction package. Which is often the first point when new users & devs get in touch with TYPO3 or even evaluating it.

**Comment by benjaminkott** [comment]
@jvanderkroon, @khaefeli hey guys, i am removing this for now. If nobody wants it back in everything is ok ;)

**Comment by khaefeli** [comment]
cool. thanks.
