### ISSUE TITLE
Add develop branch

### ISSUE THREAD

**Issue by No5251** [benjaminkott/bootstrap_package#129]
Please create a "develop" branch and keep "master" stable.

**Comment by cedricziel** [comment]
I would very much welcome this.

Also, branching makes contributions a lot easier.

**Comment by benjaminkott** [comment]
Hey @No5251, @cedricziel, i am always open to anything - but I don`t see a really need for that since for me master is always the latest development state. We are currently using tags to provide flags for stable versions that are also listed under releases. Also the development is straight forward and there will be no bugfix releases for older releases - at least nothing like that is planned.

The only thing that would change with having a dev branch would be the die mega merge that is created on release.

**Comment by cedricziel** [comment]
It worked 'til now. Let's see what happens :)

Also folks should check out Tags to production boxes. I'm with you in that regard.
