### ISSUE TITLE
[TASK] Carousel: Make headline settings modifiable or no headline at all

### ISSUE THREAD

**Issue by newenduser** [benjaminkott/bootstrap_package#188]
Hi guys,

I hope this is the right place to post - as you will certainly realize I am not a developer but just an enduser.

Here is my issue:
On my start-page I have two carousels, one on the top and one on the bottom. For the one on the bottom I would like to have a) a background image and a headline or b) the background image only. Unfortunately the headlines are always defined as "H1" which is not good for SEO reasons. Therefore I would like to change the "H1" to e.g. a "H4" or have no headline at all (but entering a headline is mandatory).

Is there a way that you either add a dropdown for users to change the settings of the used headline or make headlines simply optional?

Thanks a lot in advance!

**Comment by webian** [comment]
Hi @newenduser.
please have a look at this pull request that I made https://github.com/benjaminkott/bootstrap_package/pull/140 that should make what you need.
The pull request has not been merged but you can see how it works.
Bye.

**Comment by benjaminkott** [comment]
@newenduser, @webian i get the usecase for configurable header types. this is something we can add indeed to the default setup. We do not need to print the Header to the frontend, but the field should be still required so the user can identify the elements in the backend.

**Comment by webian** [comment]
@benjaminkott maybe this issue should be analysed from the opposite:
supposing that the header of a carousel item is no more required then if the user want to identify the element in the backend (s)he should have the option to fill the header field as a BE reference, but should not be forced to fill it if it's not used in the frontend.
It's the same behavior of the normal tt_content header.

**Comment by newenduser** [comment]
@benjaminkott Perfect, sound great! This may sound stupid now, but how do we know when this feature will be integrated? Sorry to ask, but I am new here...

**Comment by benjaminkott** [comment]
@webian i can understand that, but i want also to be a bit more restrictive since what i am seeing in production the fields are not getting filled and making problems afterwards to identify the records - also on communication very unsupportive - like the 3rd element from in the right column. 

@newenduser will have to look when to have time to add this, but - 1. youll get notifed when i close this issue or some action is taken in here. when its in the code it will come up with the next release thats not really timed currently mostly with the releases of the new typo3 7.x versions. Whats inside an release you can lookup here https://github.com/benjaminkott/bootstrap_package/releases

**Comment by newenduser** [comment]
@benjaminkott Thanks for the explanation! I am looking forward to your new release, have a great weekend!

**Comment by benjaminkott** [comment]
@webian @newenduser had some time this evening, made 2 patches, for configurable header layouts and a standalone backgroundimage type

**Comment by newenduser** [comment]
@benjaminkott Thanks, that was fast! I am looking forward to testing it once the update is out!
