### ISSUE TITLE
$GLOBALS["TBE_STYLES"]["logo_login"] is deprecated

### ISSUE THREAD

**Issue by Chrissitopher** [benjaminkott/bootstrap_package#194]
> $GLOBALS["TBE_STYLES"]["logo_login"] is deprecated since TYPO3 CMS 7 and will be removed in TYPO3 CMS 8, please use the backend extension's configuration instead.

Fix it!

**Comment by NeoBlack** [comment]
there is nothing to fix

**Comment by benjaminkott** [comment]
Hey @Chrissitopher, i am aware of that deprecation, because i have deprecated it. Since ext_conf_template is not version aware currently, and its only a deprecation this should not be a problem. 

It´s gone when we hit version 8, as long we support 6.2 we need to find a way around it. But your deprecation log is hopefully disabled in production mode so this is not a high priority problem currently. 

But i´ll keep it as note here.

**Comment by Chrissitopher** [comment]
This one got solved with 42001a961dc6103df84dfd507711b1d15d3e8de4.
