### ISSUE TITLE
Image intext is not aligning right

### ISSUE THREAD

**Issue by JeppeDonslund** [benjaminkott/bootstrap_package#270]
Hi, thanks for det fantastic bdist package.

I have the problem that when using "image in text right" in content elements, the image is not to the rigt, it is more like over the text.
If I do not include bootstrap_core ind the template, it works, but then the images is not responsive.

Is it a bug or a missing feature? Og do I need to do something?

**Comment by benjaminkott** [comment]
hey, i have sadly no idea what bootstrap_core does, but the option "image intext" left and right should work if the image is not too big in 6.2.15.

Also i remove this option in 7.0.0 because with the responsive image settings ist actually to hard to get the with of image correct, also for the editor nur really "intuitive".

**Comment by benjaminkott** [comment]
i am closing this issue now, because it seems there are no more questions to this topic.
