### ISSUE TITLE
Rebase instead of merge

### ISSUE THREAD

**Issue by webian** [benjaminkott/bootstrap_package#310]
I can be wrong but if we rebase instead of merge we should avoid the merge-commit hell and have a more clear repo log:
http://stackoverflow.com/questions/16358418/how-to-avoid-merge-commit-hell-on-github-bitbucket

**Comment by webian** [comment]
Correction: it's rebase **before fast-forward** merge (not instead of merge)

**Comment by cedricziel** [comment]
Hey @webian ,

Thank you for reporting the issue. Let me get straight to the point(s):

1. I see no merge commit "hell"
2. This is a Version Control System that has a different scope than pleasing the eye.
3. Merge commits are far more important than you think

And the most important one:

We do this in our spare time. Pressing a button from a UI is by far quicker and a time-saver instead of having to go down to merging everything manually.

I vote for no and instead ask you to filter your git log output appropriately.

I'll close this one, but feel free to explain why this is disturbing for your use case.

Thank you for reporting - I hope I wasn't too pressing :)

**Comment by webian** [comment]
@cedricziel you can do [1] instead of [2].
[1] is more clear than [2] that generates an unuseful commit.
Just select "Rebase and Merge" instead of "Merge pull request" or maybe you can ask @benjaminkott how to.

![](http://i1356.photobucket.com/albums/q732/ian388/2016-10-17%2013_48_15-Commits%20%20benjaminkott_bootstrap_package_zpszg67kaki.png)

**Comment by cedricziel** [comment]
Thanks for the hint! Yeah, it's available for quite some time now-yet I still see no value in it :)

What is it, that bothers you? I for once prefer a precise history that doesnt exclude merge events, since they are precious pieces of information
