### ISSUE TITLE
Gridelement "Wert nicht erlaubt -1" bei Typo3 7.6.9 bei neuen Content im Gridcontainer

### ISSUE THREAD

**Issue by eeels** [benjaminkott/bootstrap_package#351]
bei Typo3 7.6.9 und bootstrap_package	7.0.2
wenn ein Elemnt zuvor im Spalte normal ist und dann in das Gridelement geschoben wird tritt der Fehler nicht auf.
bei deaktivierter TCA/Overides/tt_content.php oder älterer Version kommt es nicht zu  einen Fehler.

**Comment by webian** [comment]
Add this line at the end of that file:
`\TYPO3\CMS\Core\Utility\ExtensionManagementUtility::addToAllTCAtypes('tt_content', '--div--;LLL:EXT:gridelements/Resources/Private/Language/locallang_db.xlf:gridElements, tx_gridelements_container, tx_gridelements_columns');`

**Comment by benjaminkott** [comment]
@eeels i´ve tested the setup. gridelements is working fine with some adjustments to the configuration.i only can reproduce this issue when there is no container setup defined for gridelements.

https://github.com/benjaminkott/bootstrap_package/wiki/Use-GridElements-with-the-BootstrapPackage-greater-than-7.0.0

**Comment by timri** [comment]
I have also been hit by this.
The problem seems to be (IMHO), that bootstrap_package rewrites/replaces TCA[tt_content][types][*]
So any adjustments done by extensions that are loaded before bootstrap_package (f.e. gridelements) are lost.
This particular problem here can be worked around by adding:
```
if (\TYPO3\CMS\Core\Utility\ExtensionManagementUtility::isLoaded('gridelements')) {
	\TYPO3\CMS\Core\Utility\ExtensionManagementUtility::addToAllTCAtypes('tt_content',
		'--div--;LLL:EXT:gridelements/Resources/Private/Language/locallang_db.xlf:gridElements, tx_gridelements_container, tx_gridelements_columns');
}
```
to the bottom of Configuration/Overrides/tt_content.php
(however any modifications done by other extensions could also be lost, if those are loaded BEFORE bootstrap_package, which they might be, if they do not depend on bootstrap_package)

So a proper solution would be to not unconditionally overwrite the TCA.
(or does Typo3 allow to enforce a particular loading order, if the extensions are not dependant of each other, i.e. force bootstrap_package be loaded before all other extensions?)

**Comment by benjaminkott** [comment]
@timri already talked a lot about this in the slack channel also with Jo Hasenau (the gridelements guy) this is a general problem with gridelements - make sure that you install grid elements after you install everything else you need then everything is fine - otherwise you need to load add the stuff manually in a provider extension.

currently typo3 is missing a loading order to avoid exactly this behavior ;(

**Comment by typo3ua** [comment]
Hello, everyone!
I can't get support the "gridelements" for the "bootstrap_package"
**Step 1:**
![setup](https://cloud.githubusercontent.com/assets/638022/18610436/08b8d05c-7d25-11e6-9d54-fac098b69029.png)
**Step 2:**
I'm added to `/Configuration/TypoScript/setup.txt` this [code...](https://github.com/benjaminkott/bootstrap_package/wiki/Use-GridElements-with-the-BootstrapPackage-greater-than-7.0.0) 
**Step 3:**
I'm added the GridElements.html to `/Resources/Private/Templates/ContentElements/`
**Step 4:**
I'm added GridElements configuration to `/Configuration/PageTS/GridElements/setup.txt`
**Step 5:**
I'm added content element on page in backend.
![setup1](https://cloud.githubusercontent.com/assets/638022/18610502/c5334a2c-7d26-11e6-9024-6045ce090b7b.png)
**Step 6:**
In left colemn added content element "header"
![setup2](https://cloud.githubusercontent.com/assets/638022/18610508/e5e5f0a8-7d26-11e6-9854-f098776a49da.png)
**Step 7:**
Clear cach...
**Step 8:**
I went to the page, and it is empty.
**What is wrong?**

**Comment by md-akenzo** [comment]
@benjaminkott are there any updates to this behavior? The Workaround from @timri does work but is not a solution with regard to updates. The installation order does not seem to work properly. Again and again the same result. In the Main Template the order is (1. Bootstrap Package, 2. grid_elements).

**Comment by benjaminkott** [comment]
@md-akenzo currenlty trying to resolve this issue on core side - there is a major inconsistency in handling this. but the guide should still work https://github.com/benjaminkott/bootstrap_package/wiki/Use-GridElements-with-the-BootstrapPackage-greater-than-7.0.0

prepared a proposal that should solve this issue https://review.typo3.org/#/c/52132/ also in talks with joe about this

**Comment by md-akenzo** [comment]
@benjaminkott the guide doesnt work. But if add the 4 lines code from @timri to Configuration/TCA/Overrides/tt_content_element_textmedia.php the Column will be right and the Type is correct (Create new element in Grid Elements and first time saving). 

![unbenannt-1](https://cloud.githubusercontent.com/assets/22198673/24248509/14561c24-0fd0-11e7-841b-b652af5fadea.png)
