### ISSUE TITLE
no nav_title for menus

### ISSUE THREAD

**Issue by brrrrrrrt** [benjaminkott/bootstrap_package#364]
on various Menu Types like "Thumbnail Menus" or "Menu of Subpages to these Pages" the nav_title is ignored.

i already tried:

```
tt_content.menu.thumbnail_dir {
    dataProcessing {
        10 {
            titleField = nav_title // title
        }
    }
}
```

but this doesn't work either :(

**Comment by benjaminkott** [comment]
@brrrrrrrt thumbnail menus are incorrectly accessing `{page.data.title}` instead of `{data.title}`.
Data does always contain the raw data while the data on first level is processed.

nav_title // title is also already the default, there is no need to set this except you want to change this.

Will provide a bugfix for released versions.

**Comment by benjaminkott** [comment]
@brrrrrrrt should be resolved please reopen if it still fails
