### ISSUE TITLE
Images fade in doesn't work if not cached in browser and slow connection

### ISSUE THREAD

**Issue by webian** [benjaminkott/bootstrap_package#379]
This image fade in:
https://github.com/benjaminkott/bootstrap_package/blob/master/Resources/Public/Less/Theme/misc.less#L120-L121
doesn't works if the image is not already in the cache and the connection is not fast enough.
The image will appear instantly instead of fading in gracefully.

Unluckily, the cases that doesn't make this to work are quite common in the real world.

It would be nice to have this effect working also in these cases, maybe checking if the image is loaded before changing its opacity to 1?

Side questions:
1) Is there a reason to make the opacity start from 0.3 instead of 0?
2) Why a so short fade in time (0.3)?

**Comment by webian** [comment]
I temporarily solved this removing [this line](https://github.com/benjaminkott/bootstrap_package/blob/master/Resources/Public/JavaScript/Src/jquery.responsiveimages.js#L113) and adding this code to `$(document).ready`:
```
$('img.lazyload').on('load',function(){
    $(this).css("opacity", 1);
});
```

**Comment by s-leger** [comment]
If i recall correctly, the load event dosen't always fire on some browsers -typically when allready in cache-, so i choose to not rely on it at all.

As for the opacity, a better option may be to add a ".loaded" class instead of styling the tag directly, so you're free to decide witch transition to add to your images (scale, fade and so on).

```
this.$element.addClass("loaded");
```
We also have to ensure ".no-js" cases dosen't fail.

**Comment by benjaminkott** [comment]
Image handling has been completeley reworked, this should not be a problem anymore. Please see https://github.com/benjaminkott/bootstrap_package/commit/0d35fdcb597249715e2c9eece8f3d2ac57b7de94 for all the changes.
