### ISSUE TITLE
Translation issue on carrousel

### ISSUE THREAD

**Issue by tsh-gmbh** [benjaminkott/bootstrap_package#397]
Hello,

at first: thank you for this awesome package! I love it!

In the table "tx_bootstrappackage_carousel_item" the sys_language_uid field will not be set to the target language, if i try to translate the carrousel element. So it's not displayed in the target language.

I tried to debug and find a difference between the accordeon and carrousel handling of translation, but i can not find any problem.

My config:
bootstrap_package
bootstrap_grids
TYPO3 7.6.12

All extensions are installed in the latest version.

**Comment by webian** [comment]
Hello @tsh-gmbh and @benjaminkott 
I came here to report an issue and found this one that, if I understood correctly, is similar to mine.

If I set a carousel language to "[All]" then its elements are displayed only in the default language.
This is because the field `sys_language_uid` of the `tx_bootstrappackage_carousel_item` is 0 and not -1.

Also, actually is not possible to set the language of the carousel items from the BE but if I manually set `sys_language_uid` to -1 then the items are visible in all languages.

**Comment by benjaminkott** [comment]
@webian sounds like a FormEngine bug to me. Language uids are handled by the TYPO3 core itself and we are not doing anything besides using the configuration. There is also a DataHandler that we are currently avoiding with https://github.com/benjaminkott/bootstrap_package/commit/f46a63177d3d3e6eb5971cdfaba356845f053c1d?diff=unified this patch.

**Comment by webian** [comment]
After hours of testing and debugging (I'm not expert about this DataHandler stuffs) I am unable to find the source of the problem.

I tested with "File Links" and it behaves correctly. Even if its childs (sys_file_reference) always have sys_language = 0, they are displayed only if the parent (tt_content of type `uploads`) is set in the displayed language or language [All]. Practically, the parent commands.

Instead in Bootstrap Package carousel or accordion or panel are the childs that command they are displayed only if their sys_language is the one of the page. Since sys_language = 0 (if not manually changed in the DB) they are displayed only in the default language.

@benjaminkott do you know if there's a way to make carousel & co. to behave like "File Links"?
Or at least we should allow the editor to change the language of the childs (items) to walk around this "bug".

**Comment by benjaminkott** [comment]
@webian will do some tests on that and try to figure out the problem, current behavior is not correct

**Comment by benjaminkott** [comment]
@tsh-gmbh @webian i think, that this one seems to resolte the issue https://github.com/benjaminkott/bootstrap_package/commit/571192e5d8ac365764952ac220e9d42c1f446f6f

- Translating works fine
- All Languages also works fine

Tested with current master of TYPO3 8.7

**Comment by benjaminkott** [comment]
issue seems to be resolved, closing this for now.
