### ISSUE TITLE
Better support of OnlineMedia

### ISSUE THREAD

**Issue by georgringer** [benjaminkott/bootstrap_package#400]
OnlineMedia adapters can bring new types which can't not be rendered by `<f:image />` but are still from type image.

I propose to check in `Resources/Private/Partials/ContentElements/Media/Rendering/Image.html` the file type against `$GLOBALS['TYPO3_CONF_VARS']['SYS']['mediafile_ext']` and use `<f:media />` if found in there.

what do you think?

**Comment by benjaminkott** [comment]
@georgringer currently the types are strict, so you have to decide what you have to decide upfront what you want to use. that means if you want to use media you have to use the media element otherwise the image element a mixture is not intended by concept. This makes it more easy to maintain templates and be more specific about what you are doing. 

Can you give me an example for additional online media?

**Comment by benjaminkott** [comment]
@georgringer i like the idea of supporting this, but is has to be a new content element. i think it should not be handled by textpic, images, textmedia or media.  The only way to handle it correctly in all cases would be a new content element that only takes care of rich media. personally i would also prefer a content element for each type.

**Comment by benjaminkott** [comment]
@georgringer i am closing this for now, feel free to open it again if you thing we should figure out a solution here.
