### ISSUE TITLE
Layout changes after update from 7.0.5 to 7.1.0 

### ISSUE THREAD

**Issue by adrienjacob** [benjaminkott/bootstrap_package#429]
Sorry if this issue has been raised already, I'm probably not the first one to wonder about this, but I couldn't find a related thread... So here it is : after updating from 7.0.5 to 7.1.0 (tried on both Typo3 v7 and v8.6), I noticed the layout got slightly changed : different fonts, some margins changed etc.

Therefore, I'd like to understand what we are supposed to do with these updates, if we want to keep everything looking the same
- Simply don't perform updates (are they needed for security reasons, compatibility with v8, etc. ?)
- Make a backup copy of `/Resources/Public/Less`, `/Resources/Public/Fonts` and `/Configuration/TypoScript/constants.txt`, and call them through typoscript with `page.includeCSS.theme = SomePath/Less/Theme/theme.less` and `<INCLUDE_TYPOSCRIPT: source="FILE:SomePath//bootstrap_package/constants.ts">`. This solution somehow worked (I had the same look in 7.1.0 and 7.0.5), but it doesn't feel right...
- Or... a better solution perhaps ?

Thanks for your advice.

**Comment by PascaleBeier** [comment]
Bootstrap was updated to v3.3.7, see https://github.com/benjaminkott/bootstrap_package/commit/bcfd9ef16ca3e6ab5934b1f2f037b705c6fa05e8

**Comment by benjaminkott** [comment]
The bootstrap_package will evolve over the time, that also includes layout adjustments, new features and all kinds of things to make the work more easy overtime. While 7.0.5 to 7.1.0 is a minor version it can include some adjustments. While a bugfix update will never include such adjustments and will only contain bugfixes.

The intended workflow is that you use your own sitepackage to extend the bootstrap package and deliver your own css. A helper for generating such a package can be found here: https://sitepackagebuilder.com/

The different fonts came in as feature, since you are now able to select these direclty in the bootstrap_package and you are not limited anymore to the font selections i did before. Margins have been adjusted to add space where space was missing to provide a more modern look.

As mentioned, if you do not want those updates, you have to provide your own css and only use the rendering definition below.
