### ISSUE TITLE
Typoscript Setup Settings for Mainnavigation doesn't work.

### ISSUE THREAD

**Issue by schorsch8878** [benjaminkott/bootstrap_package#435]
I set the Levels for the Mainnavigation to 4 but it doen't work. Is there a possibility to add more levels? I need more. (TYPO3 7.6.16 with Introduction Package)

 dataProcessing {
            10 = TYPO3\CMS\Frontend\DataProcessing\MenuProcessor
            10 {
                levels = 4 
                includeSpacer = 1
                as = mainnavigation
               }

**Comment by benjaminkott** [comment]
@schorsch8878 the correction is totally fine - the problem here is that you need also to adjust the main menu template that is processing the data. you can simply overrride the partial in your sitepackage. https://github.com/benjaminkott/bootstrap_package/blob/master/Resources/Private/Partials/Page/Navigation/Main.html

**Comment by bmsail** [comment]
Hi Benjamin Kott,
great work, thank you!
I´m running Typo3 8.7.1 with bootstrap_packege 8.0.2 without changes
I have the same problem with mainnavigation. Only one level is shown, even when I set levels = 3.
The same problem I do have in mobile view. The Hamburger menue obly displays one level.

How can I adjust Main.html to get second level displayed.

Thank you.
