### ISSUE TITLE
please insert old attributes to file Gallery.html

### ISSUE THREAD

**Issue by gilas1959** [benjaminkott/bootstrap_package#449]
Regards: bootstrap package v.8.0.0

Probem: the template file:

EXT:bootstrap_package/Resources/Private/Partials/ContentElements/Media/Gallery,html

was modified since latest version 7.1.0
but you forgot to add some code to get the columns at the same size.

Please insert here:
    <div class="gallery-row row">
the attribute:
    data-equalheight="container"

and here:
 <div class="gallery-item" ...>

the attribute:
data-equalheight="item"

this is very useful to get the column at the same size via CSS (have a look to my extension, key: rollovercollectiion4)

thank you very much

**Comment by benjaminkott** [comment]
@gilas1959 hey, it was removed because we moved to flexbox at this point, this makes it more easy to control the equalheight via css and reduces the need of javascript. Flexbox is now save to use (http://caniuse.com/#search=flexbox) and you only need to adjust your css settings. Please have a look here.

https://github.com/benjaminkott/bootstrap_package/blob/master/Resources/Public/Less/Theme/gallery.less#L4-L17
