### ISSUE TITLE
split configuration+content elements+helpers and template into two extensions?

### ISSUE THREAD

**Issue by dni** [benjaminkott/bootstrap_package#457]
Hi!

I have a question, i really love the configuration and the content elements of this extension, and i already used all the templates helpers an stuff in 7.6.

Now im facing the same problem again, i don't want use the templating like it is now in the extension, i have my own ideas of the template without to much configuration and also without less php and stuff. 

last time i slaughtered the extension into pieces so only the configurations and content elements where left and that i could purely use my templating, which wasnt very good to maintain if you guys had updates and fixes.

now facing the same thing again with v8 i was wondering if there is any way to split up your package into two separate things like configuration and templating. i think this kind of thing would be useful for more people like me.

what do you think about that? you know what i mean?

**Comment by benjaminkott** [comment]
Hey, while i can understand your request, the purpose of this extension is to provide an example and best practices how to structure your sitepackages and tries to cover all kinds of areas. Since i´m more or less on my own maintaining this, it will be far more complicated to have all packages in sync. And compatible with master and every new release.

The best suggestion i can give you is to create your own sitepackage and make it best to fit your needs.
Feel free to take whatever you need from the bootstrap_package and redistribute it as you like.
