### ISSUE TITLE
span-Tag in bodytext is replaced with p-Tag with latest version 9.0.0

### ISSUE THREAD

**Issue by zzzooorrrx** [benjaminkott/bootstrap_package#488]
span-Tag in bodytext (source mode) in textpic-CE is replaced by p-Tags
Before updating to version 9.0.0 I used 8.0.4 and there was the same issue with div-Tags and span-Tags

This was reproduced also on a clean 8.7.8 install.

I added in Configuration/RTE/Default.yaml
`processing:
    ## Tags that are allowed outside of paragraphs
    allowTagsOutside: [address, article, aside, blockquote, footer, header, hr, nav, section, div, span]`
but nothing changed.

Also address, header (which I tried) are replaced.

I'm not sure if this an issue of bootstrap_package or core.

WEB » Info » Page TSconfig is just
RTE.default.preset = bootstrap

typo3 8.7.8
bootstrap_package 9.0.0

**Comment by benjaminkott** [comment]
Well, while the div is sadly a side effect that i was not aware until now.  DIVs do not have really good support by the rich text componend and should be avioided to be used. Problem is that since they are added its quite impossible to remove them again by using the interface. With the last update we added support for wrapping existing elements in a div with the class well by clicking the new button in the RTE. We needed to extend ckeditor for that, so you will not hit the described problem.

![image](https://user-images.githubusercontent.com/3243119/33491317-1d9e89e0-d6ba-11e7-82de-43d24191c23c.png)

Span-Tags are currently only allowed within block elements to apply classes to parts of the text and not the whole element. Intended usage is to highlight some words, change capitalization or something like that. This behavior matches the TYPO3 Core, except divs are currently allowed as container.

![image](https://user-images.githubusercontent.com/3243119/33491680-475cc516-d6bb-11e7-975b-7a153477300b.png)

What excactly are you trying to achieve?
Manually editing the source of the rich text component is always a bad idea, and should only be used to correct errors that the rich text component could not resolve itself.

**Comment by zzzooorrrx** [comment]
The site is an update from existing content. There are dozens of CE where text/icons are inserted in bodytext.
Example:
`<div class="texticon texticon-left">
	<div class="texticon-icon texticon-size-default texticon-type-circle">
		<span class="texticon-inner-icon glyphicon glyphicon-link" style="color: #9c9c9c;background-color: transparent;"></span>
	</div>
	<div class="texticon-content">
		<a href="t3://page?uid=79" title="Detaillierte Informationen zu abc">ABC</a>
	</div>
</div>`

**Comment by zzzooorrrx** [comment]
cups where is the code gone? 
Code:
<div class="texticon texticon-left">
	<div class="texticon-icon texticon-size-default texticon-type-circle">
		<span class="texticon-inner-icon glyphicon glyphicon-link" style="color: #9c9c9c;background-color: transparent;"></span>
	</div>
	<div class="texticon-content">
		<a href="t3://page?uid=79" title="Detaillierte Informationen zu iMove-F">iMOVE-F Büromöbel</a>
	</div>
</div>

**Comment by zzzooorrrx** [comment]
Code problem. now as image

<img width="869" alt="bildschirmfoto 2017-12-01 um 17 39 20" src="https://user-images.githubusercontent.com/20296470/33492906-bc14d94a-d6be-11e7-8b5d-7906bcadf038.png">

**Comment by benjaminkott** [comment]
well that was never intended to be used like that... also wondering how this worked anyways in the first place. the only way to get this working correctly is to add a custom ckeditor widget so its also editable by the editor without needing to enter the source code. otherwise it will break by almost everytime you move around. content in that element. Also the current plugin for adding the divs with the "well" class need to be sighlty more strict in its behaviour. There is no easy way to get this right.

Sorry, that was working around the provided stuff. And i cannot cover such Stuff.
I´ve added options/ways you can resolve this issue yourself, also addet some estimated time so you can get an idea how to solve this properly.

Option a) 
Convert current elements to HTML content elements, no further adjustmends nessesary.
Finding content elements using sql and write an update script for that. 
Estimated Worktime: ~2 Hours

Option b)
Adding the span tags also the parsefunc and ckeditor and hope this works.
https://github.com/benjaminkott/bootstrap_package/blob/master/Configuration/TypoScript/Helper/ParseFunc.typoscript#L64-L68
Estimated Worktime: ~30 Minutes and hope it works

Option c) 
**THE ONLY WAY I CAN RECOMMEND**
Write a custom CKEditor Widget that can handle your stuff and adapt configuration, https://docs.ckeditor.com/ckeditor4/docs/#!/guide/widget_sdk_tutorial_1, send pull request and i can review to merge this if you like, also needs to be to handle multiple iconsets like the intendes way to use this - text and icon.
Estimated Worktime: ~2-3 Days

**Comment by zzzooorrrx** [comment]
thx for your reply and your options. will talk about that and come back later.
