### ISSUE TITLE
Page cache disabled in conjunction with EXT:realurl

### ISSUE THREAD

**Issue by w3dev-dk** [benjaminkott/bootstrap_package#535]
With a default, composer based, TYPO3 CMS 8.7.16, EXT:bootstrap_package 9.1.1 and EXT:realurl 2.2.1 we are experiencing caching issues (page cache disabled) - debugged with admin panel.

I have tracked down the issue to the following in [SYS][systemLog]:

```
26-06-18 13:11 - cms: $TSFE->set_no_cache() was triggered. Reason: Bad "L" parameter ("1") was detected by realurl. Page caching is disabled to prevent spreading of wrong "L" value.. Caching is disabled!
26-06-18 13:11 - cms: $TSFE->set_no_cache() was triggered. Reason: Bad "L" parameter ("2") was detected by realurl. Page caching is disabled to prevent spreading of wrong "L" value.. Caching is disabled!
```

The site is not configured with any extra languages, yet the bootstrap_package predefines to extra languages 1 & 2 in its TypoScript constants.

https://github.com/benjaminkott/bootstrap_package/blob/72e277cd24f4d05d2731f3281bb6ae28cc43a565/Configuration/TypoScript/constants.typoscript#L86

Should this not be changed to `languageValue = 0` so a default installation without any additional languages would work out of the box?

**Comment by benjaminkott** [comment]
@w3dev-dk thx a lot for the issue, i was not aware of the behavior of realurl here.
I´ve always override the settings in my projects and had no problems with that since it always was configured correctly.

```
page.theme.language.languageValue = 0
page.theme.language.enable = 0
```

Sadly i can only suggest to do the same until the 10.x version of the bootstrap package will be released. We have completely reworked the language menu and langauge processing here, so there is no configuration nessesary anymore. Please see https://github.com/benjaminkott/bootstrap_package/commit/cf9df4d1487f5f7e715822c5855f3b0d1274c576 for reference.

All changes we would do now in this area would lead to problems with existing installations and cause new problems with the introduction package that is using the boostrap_package.

**Comment by benjaminkott** [comment]
I will close this issue for now, again thx a lot for your feedback and we are sorry that we cannot take your suggestions for now. Please feel free to come up with new suggestions and adjustments you may need to be more productive.

**Comment by w3dev-dk** [comment]
Hi @benjaminkott 

That´s alright. I have already overridden the configuration in our base installation package. I will add a note to remind me to remove it again when version 10 is available and stable.

I´m sorry that I did not check the master branch. I will try to remember to look their next time to see if the issue has been resolved :)

Have a nice evening

**Comment by mediaessenz** [comment]
If any other poor soul out there has a BP 7 running with the same problem, just add this TypoScript to your setup (after including the bp ts):
page.10.dataProcessing.40.special.value = 0
