### ISSUE TITLE
Background Image Size

### ISSUE THREAD

**Issue by schorsch8878** [benjaminkott/bootstrap_package#595]
The Background Images e.g. of Carousel ar always 1100px width. Where can I change this? Thanks

**Comment by benjaminkott** [comment]
@schorsch8878 please keep the information about what typo3 version and what version of the bootstrap package you are using. otherwise its hard to tell what to do.

i am assuming now youre on the latest version because i´ve reduced the size from 1200 to 1100, and there should be more than one image be loaded but i guess you are talking about the desktop version.

the template responsible for rendering the background images in carousels can be found here:
https://github.com/benjaminkott/bootstrap_package/blob/master/Resources/Private/Partials/ContentElements/Carousel/General/BackgroundImage.html

You can override this in your sitepackage and adjust it to your needs.

**Comment by blueamerican** [comment]
i also have a question concerning this:
for me the image width per default is too small:
if i have a screen size of 995 px, i get an image, which has only a width of 920 px.
This is too small, if the image is full witdh, i guess.

```
lib.contentElement {
settings {
 responsiveimages {
            variants {
                default {
                    breakpoint = 1200
                    width = 1100
                }
                large {
                    breakpoint = 992
                    width = 920
                }
                medium {
                    breakpoint = 768
                    width = 680
                }
                small {
                    breakpoint = 576
                    width = 500
                }
                extrasmall {
                    breakpoint = unset
                    width = 374
                }
            }
   }
   }
```
