### ISSUE TITLE
ipad gen 3 is displaying incorrectly Typo3 9.5.1 website using the official introduction package

### ISSUE THREAD

**Issue by Tonyt8** [benjaminkott/bootstrap_package#613]
# Support
Hello,
Has any one had the below issue?
Can any one help me out with this?

I am not able to view a Typo3 9.5.1 website with the official introduction package on a ipad gen 3 running ios 9.3.5 using Safari.
I have made 2 fresh/clean installed test websites at different locations. I have only installed the "The official Introduction Package"(4.0.1 (02.10.2018) ) -  bootstrap_package 10.0.1-10.0.99
Both websites act as if the CSS is not loading when viewed on the ipad.
All other devices correctly display the  2 websites as expected.

Many thanks.
Regards,
Tony

**Is your question related to a problem? Please describe.**

**Comment by benjaminkott** [comment]
Hey, currently no idea - tested only on more modern devices - can you provide some screenshots?

**Comment by jokumer** [comment]
This is iOS 9.3 related.
I tried with Safari, Chrome, Opera
Bootstrap4 supports the latest, stable releases of all major browsers and platforms.
iOS 9.3.5 (2016) and 10.3.3 (2017) are no longer maintained versions.

![bootstrap-package.com top](https://user-images.githubusercontent.com/6431813/49545933-6030b380-f8df-11e8-9f6c-9b8ded13e41c.png)
![bootstrap-package.com bottom](https://user-images.githubusercontent.com/6431813/49545898-3f685e00-f8df-11e8-93a9-f60371218caa.png)

**Comment by Tonyt8** [comment]
Hi,

Thank you for your replies.
I need to apologize, I overlooked something in the basic setup. I should have know better. **I now have the test websites displaying correctly on a ipad gen 3.**
I forgot to install the "static template" "Bootstrap Package: Bootstrap 3.x (Less) (bootstrap_package)" to the website root template.
With the extra static template added the website is view able on an ipad gen3.

Regards,
Tony

**Comment by philippmaurer** [comment]
Hi,

We have the same Issue with an iPad Air 2 running iOS 10.2.1 and an iPad 2 that runs iOS 9.3.5. The bug is **not** present on an iPad 3 runnding iOS 11.2.6.

The bug is not only present on our website (www.roberta-home.de) since switching to bootstrap_package 10, but also on the current official Typo3 Package website (www.bootstrap-package.com). The issue is equivalent to the screenshot that was already commented above from **jokumer**.


I located the problem to be in the following CSS code in the (generated) CSS file /typo3temp/assets/bootstrappackage/css/theme-{hash}.css : `@supports (position: sticky) {position:sticky;top:0;z-index:1020;}`

The correct code for this seems to be shown in EXT:/bootstrap_package/Resources/Public/Css/bootstrap4-theme.min.css:
`@supports (position:sticky){.sticky-top{position:sticky;top:0;z-index:1020}}`

Somehow the `.sticky-top{}` part is not generated correctly, which results in the incorrect css syntax that stops the iOS Safari 9/10 version from interpreting the CSS any further. Therefore this might be present on other devices / browser engines as well.

This can be validated by taking a look on the previous and next command in the CSS file in the developer console for the iPad:

- `.fixed-top,.navbar-mainnavigation.navbar-fixed-top{...}` 
This is the command that **proceeds** the incorrect syntax part. It is shown as a CSS rule for the sticky header in the developer console.
<img width="994" alt="screenshotdevnext" src="https://user-images.githubusercontent.com/10925094/53896300-05207100-4034-11e9-9954-79839dd89f5e.png">

- `.sr-only {...}`
This is the command that **follows** the incorrect syntax part. The start-page of the typo3 bootstrap package website has an element with the calsses `sr-only sr-only-focusable`. The above rule is **not** shown as a CSS rule for that element in the developer console.
<img width="999" alt="screenshotdevprev" src="https://user-images.githubusercontent.com/10925094/53896271-f89c1880-4033-11e9-9140-121409e0ad82.png">


If any other information is required please let me know.

Best regards and thanks for the awesome project,
Philipp

**Comment by benjaminkott** [comment]
legacy css incompatibility
