### ISSUE TITLE
PhotoSwipe lightbox shows no description if no title is given

### ISSUE THREAD

**Issue by Moongazer** [benjaminkott/bootstrap_package#626]
If an image has only a description but not a title given in the backend (and "Enlarge on Click" is enabled), the lightbox popup doesn't show the description. I tried to modify the `bootstrap.lightbox.js` with some slightly changes, which successfully inserts the HTML for the caption, but the caption div gets the class `pswp__caption--empty` so its still not visible in the lightbox. I coulnd't figure out where this class comes from.
```
addCaptionHTMLFn: function(item, captionEl, isFake) {
    captionEl.children[0].innerHTML = '';
    if(item.title) {
        captionEl.children[0].innerHTML = '<div class="pswp__caption__title">' + item.title + '</div>';
    }
    if(item.caption) {
        captionEl.children[0].innerHTML += '<div class="pswp__caption__subtitle">' + item.caption + '</div>';
    }
    return true;
},
```
(Also I removed the `return false;` statement, as it seemed to have no effect if true or false comes back)

**Comment by wtfred** [comment]
Hello,
I had to deal with it once, to fix it i overrided bootstrap_package/Resources/Private/Partials/ContentElements/Media/Type/Image.html to replace line 12 attributes `title` and `data-lightbox-caption` by `title="{f:if(condition:file.properties.title, then:file.properties.title, else: file.properties.description)}" data-lightbox-caption="{f:if(condition:file.properties.title, then:file.properties.description, else: '&nbsp;')}"`
(if data-lightbox-caption is empty, photoswipe will automatically fill it with the title, that's why i make it to nbsp)
If that can help :)
