### ISSUE TITLE
Mac Safari Browser 9.0.3 + 9.1.3 incompatibility? www.bootstrap-package.com isn't displayed correctly

### ISSUE THREAD

**Issue by zeichensatz** [benjaminkott/bootstrap_package#637]
Using Safari 9.0.3 on my Mac the site www.bootstrap-package.com isn't displayed correctly.
Run into this problem when updating my website to bootstrap-package 10.0.5 (TYPO3 9.5.4).
The problem only occurs with bootstrap4. When switching to bootstrap3 within the bootstrap_package extension, the problem disappears.
Tried a few other bootstrap4 theme sites. The problem didn't occur there.
Also tested www.bootstrap-package.com on browsershots.org with Safari 9.1.3 selected. Same problem there.
The browser seems to have problems with the CSS ...
See some screenshots attached.
Sorry, I'm not a TYPO3 professional, therefore I'm not able to to solve the problem without help.
Is it a browser compatibility problem, a bootstrap4 problem or a bootstrap_package problem?

Thanks a lot for your comments!

Wolle

<img width="1109" alt="903" src="https://user-images.githubusercontent.com/45975889/51737239-66940e00-208c-11e9-999a-867c96e479f9.png">
<img width="1106" alt="903-errormessages" src="https://user-images.githubusercontent.com/45975889/51737240-66940e00-208c-11e9-8da8-713964af05df.png">
![913](https://user-images.githubusercontent.com/45975889/51737241-66940e00-208c-11e9-84a9-02b97f7b26f4.png)

**Comment by osahner** [comment]
autoprefixer-php is just a wrapper for https://github.com/postcss/autoprefixer which is a Node app.
But take a look at https://github.com/leafo/scssphp/issues/610 which mentions https://github.com/padaliyajay/php-autoprefixer.

**Comment by benjaminkott** [comment]
@osahner Great! Will have a look - seems to be active will evaluate if we can simply add this as a processing step.

**Comment by benjaminkott** [comment]
Had a quick look, the mentioned project is only a simple wrapper and he uses https://github.com/sabberworm/PHP-CSS-Parser to do the magic and only adds some rules.

The major flaw for me is that the author of the auto writes his own rulesets for prefixing. For me, this is a nogo since we would be reliant on the author updating his rule sets to match the ongoing needs. 

But I think thehttps://github.com/sabberworm/PHP-CSS-Parser is a great project that could help us if we want to build a real alternative for https://github.com/postcss/autoprefixer and bring its capabilities to the PHP world. Will play a bit around with it - maybe we can do the same as the autoprefixer project and utilize also https://caniuse.com/.

**Comment by zeichensatz** [comment]
Thanks a lot for your comments on that issue!

Wolle

**Comment by mandrasch** [comment]
Anyone stumbling about this in future (as I did now), I disabled css processing and added https://github.com/svewap/ws_scss, which has AutoPrefixer Support via csscrush

```
'EXTENSIONS' => [
        'bootstrap_package' => [
            'disableCssProcessing' => '1',
```

Adding ws_scss:

`composer req svewap/ws-scss`

And in my custom template config I used (not quite sure how to do it in 'normal' bootstrap_package yet)

```
main = EXT:template/Resources/Private/SCSS/style.scss
main.formatter = WapplerSystems\WsScss\Formatter\Autoprefixer
```

(Found via https://github.com/svewap/ws_scss/issues/11)
