### ISSUE TITLE
scss folder in Public

### ISSUE THREAD

**Issue by stat1x** [benjaminkott/bootstrap_package#643]
Hi,
I am wondering why all the scss files are located in Public folder. Do you have any explanation to it? In my opinion it should be stored under the Private one.
Thanks,
Jay

**Comment by stat1x** [comment]
I mean I don't think it is necessary to give access to this kind of files to the visitors (http://www.bootstrap-package.com/typo3conf/ext/bootstrap_package/Resources/Public/Scss/Theme/_frame.scss)

**Comment by benjaminkott** [comment]
@stat1x the less and scss parser both can enable source maps that help you to debug the compiled css files, to work best the files need to be accessible - otherwise you will be unable to jump directly into the sources. 

In addition... but on a different topic level - I think it's important to make the web more open again and help other developers to understand how the results are achieved. 

David Heinemeier Hansson has summed it up really well. 
https://m.signalvnoise.com/paying-tribute-to-the-web-with-view-source/

**Comment by stat1x** [comment]
I always have my SCSS files in a Private directory and source map is still available. I do not really agree about "making the web more open" as it can potentially increase the number of security breach.

**Comment by Moongazer** [comment]
@stat1x SCSS is not a security related attack vector in this case, so no big issue here^^

**Comment by stat1x** [comment]
@Moongazer I was speaking about "making the web more open" which means also displaying JS sources. Of course there's no security breach by showing SCSS source files.

**Comment by benjaminkott** [comment]
@stat1x thx for your feedback, I also consider making source maps of js files open is not a security risk. I am closing this issue for now.
