### ISSUE TITLE
Language detection / selection needs improvement.

### ISSUE THREAD

**Issue by benjaminkott** [benjaminkott/bootstrap_package#65]
The current position of the language menu seems to be problematic. Users on Mobile devices may not find the selection.

**Comment by newenduser** [comment]
Hi again,

@webian: Sorry that I opened a new threat. Probably I thought those "old" threads aren´t read any more.
@cedricziel: Unfortunately I cannot provide a pull request, because I really am an end user. I cannot code, I am just using what you all provide. 

Basically I just wanted to point out that the language position on the lower left (footer) simply doesn´t seem to work for users who don´t know the template. In my eyes it´s always quite important to have real users´ feedbacks. Upper right corner probably is the only position that works.

It´d be great if the selection could be brought up there - either with a flag or a globe as icon. Is this very complex and do you think any of you guys will find some time to implement it?

Thanks a lot in advance!

**Comment by webian** [comment]
@newenduser no problem, I was wondering if there was a reason that I didn't get to open a new issue. (when you reply to an issue, Github sends emails to the users that participate to the discussion so no worry, old issues are still read)

I should work on this but not really soon, sorry. Maybe a quick solution, if you know (or wanna learn) a little of jQuery is to inject a link in the main menu (CSS styled as you want) that, when clicked, will scroll the page down to #language_menu.

**Comment by newenduser** [comment]
@webian Thanks again for taking care of this issue and I will keep my fingers crossed that you will find some time for it! Thanks also for the tip with the link, although I personally think that a "cleaner" solution would be much better. I am quite sure that many out there dealing with international users would greatly appreciate the "upper right"-solution! Thanks!

**Comment by workfare** [comment]
@webian & @newenduser this is to confirm the problematic language selection.
We are working on a onepage site for an international audience with initially english and german versions but many more to come. The selection in the footer doesn't really work.
Our designer provided a solution with a globe icon. It reveals the available languages when clicked in a dropdown. I am having a hard time implementing it with Typoscript because there is no IFSUB on a onepage.
But that aside the language selection needs a better solution.
And having said that: Everything else works like a charme.
Big thank you for that!

**Comment by newenduser** [comment]
@webian Good morning (to you all)! I was wondering if there is any progress regarding the language menu position? We plan on going live with our little new multi-lingual project within the next weeks. I am just curious whether you have had time already to take a look? Not exactly knowing where you are located, please be sure that we will buy you a beer for helping us out! Have a great Thursday!

**Comment by webian** [comment]
Hi @newenduser,
I created this gist with a Javascript that moves EXT:bootstrap_package language menu to main menu
https://gist.github.com/webian/787f4993e66b9255b8cc

I hope it helps.

**Comment by newenduser** [comment]
Hi @webian,

Thanks a lot, works nicely! The only thing I don´t understand is that the mobile dropdown menu looks different to the desktop version. The colors I defined are different. This is somehow strange, since the main menu looks the same in both versions. Do you have a hint for me by chance?

Anyway, it´s good to have the language selection on the upper right now, thanks again!

**Comment by webian** [comment]
Hi @newenduser,
language items on mobile should work the same as the other menu items on mobile. The same css should apply to them cause they have the same markup. Do you have a url to give me to check it?

**Comment by newenduser** [comment]
Hi @webian! Sorry for my delay in responding! I am happy to forward the URL once we go live - this will be in a couple of days / weeks. It´s not a major issue, but it is strange in my eyes that e.g. the hover color is different once the menu is collapsed (for smaller devices). Actually I would like to show you guys the website anyway, since the template you all are working on so much helped us a lot. Thanks!

**Comment by newenduser** [comment]
@webian In October you asked for a URL to check, here it is: eventmachine.xyz. Took us a while, but I wanted to have a proper solution for us (including automatic language detection) first. If you compare the mobile and the desktop versions, you will see that the hover effect for the dropdown menu differ...and I don´t really know why... Thanks again!
@benjaminkott Benjamin, maybe you would like to have a look at the website as well - thank you so much for you all working on this template. I think we did quite a nice project with it. Thanks!

**Comment by benjaminkott** [comment]
Thanks for your report, i´ve created a new epic to collect all language related issues, or areas that could need improvement: https://github.com/benjaminkott/bootstrap_package/issues/510

Will close this issue for now, but will be referenced in the epic.
