### ISSUE TITLE
What would be the best way to move the language menu to the top?

### ISSUE THREAD

**Issue by yurigoul** [benjaminkott/bootstrap_package#662]
# Support
I would like to move the language menu to the top, next to the main menu - but at the same time I would still be able to update the bootstrap_package when future releases come along. What would be the best way, the least destructive way?

Is there a way to do that over constants or setup? Or another kind of switch?

**Comment by benjaminkott** [comment]
@yurigoul The variables for the menu are available in the template so you can render a language menu like you want to have it anywhere in the page templates. Currently there is no option that simply flipps it to the header, because its not defined how it should behave.

Meanwhile we have multiple options how you can achieve what you want.

## Option 1

You can use a sitepackage to overwrite the complete menu and adjust the template fully to your needs. 
But you will need to check on updates for the next major version yourself if the templates still match in general. Mostly recommended if you need that part completely changed.

Tempalte to overwrite: https://github.com/benjaminkott/bootstrap_package/blob/master/Resources/Private/Partials/Page/Navigation/Main.html

## Option 2

If you need less adjustments and only want to render something additional in the menu or in the header section. We introduced in the Bootstrap Package an conecpt that we are calling `DropIn` templates. The idea is to have empty placeholder templates at central places where you possible need add additional stuff, that can not been implemented in by default because its too specific or you just have no idea what a user wants to do later on with that section.

https://github.com/benjaminkott/bootstrap_package/blob/master/Resources/Private/Partials/Page/Navigation/Main.html#L21-L23

If you have a look at the following parts you see the Menu has two of these DropIn locations already available. Means you can simply overwrite one of the following templates, depending if you want to render it before or after the menu.

https://github.com/benjaminkott/bootstrap_package/tree/master/Resources/Private/Partials/Page/DropIn/Navigation

These templates are meant to be overwritten and will never have any content included. Means they are the best choice if you want to render additional elements in the header/at this point.

**Comment by yurigoul** [comment]
This is really helpful, thanks. I will go with the DropIn templates, that seems the best solution.

**Comment by benjaminkott** [comment]
I am closing this issue, please open a new one if you have problems or questions.
