### ISSUE TITLE
Lazy loading not working

### ISSUE THREAD

**Issue by McKoy61** [benjaminkott/bootstrap_package#672]
# Support
Can't get lazyloading of images working. Typo3 9.5.5, bootstrap_package 10.0.6 (SCSS), Images should fade in on entering viewport. Tried both configuration-options plugin.bootstrap_package_contentelements.preload.images = 0 and 1, no changes. Need help.

**Comment by benjaminkott** [comment]
@McKoy61 the lazyloading was dropped since it had too many problems with printing and viewport detection. It was replaced with a completely new image rendering that is also reducing the image payload a lot.

If you are looking for animations please check out https://github.com/baschte/content-animations from @baschte it also has support for the bootstrap_package.
