### ISSUE TITLE
Update scssphp lib?

### ISSUE THREAD

**Issue by TrueType** [benjaminkott/bootstrap_package#698]
The package contains the scssphp library within /Contrib/scssphp/. No version info given for the library with current v10.0.6 of this extension. But I guess it is older. I am asking, if it compiles the latest bootstrap scss library, which is given in /Resources/Public/Contrib/bootstrap4/scss/ .. more precise the index() function https://github.com/benjaminkott/bootstrap_package/blob/b8f7d912ffbba89cea638566d59cad01c87971a5/Resources/Public/Contrib/bootstrap4/scss/mixins/_breakpoints.scss#L18 called in the processing of the @mixin media-breakpoint-up https://github.com/benjaminkott/bootstrap_package/blob/b8f7d912ffbba89cea638566d59cad01c87971a5/Resources/Public/Contrib/bootstrap4/scss/mixins/_breakpoints.scss#L58 ??

- Can the problem be verified?
- Is there a possibility to update the library? 
- Is it possible to use composer to require the scssphp lib?

**Comment by benjaminkott** [comment]
@TrueType hey, I needed to add a fork the scssphp lib on the last release, the problem was that the lib was stalled during that time and we needed certain patches to get this running and compiling bootstrap 4:

current state: https://github.com/benjaminkott/scssphp/tree/applied-patches

I just checked the upstream, and it seems that they had finally started doing releases again in april!
Will check if we can apply the changes soonish. Not sure about the autoloading, but we can find a way to make this happen and prefer the composer dependency if available - did not consider it yet becasue the stalled development to be able to apply tested patches myself.

**Comment by benjaminkott** [comment]
They just switched the original repository and moved to a new namespace.
https://github.com/scssphp/scssphp

**Comment by TrueType** [comment]
I see. They are still heavily working on it, though. There is no pressure in this matter from my side. I am just happy, if I can support you with some feedback.

**Comment by benjaminkott** [comment]
Always welcome, I´ve subscribed to the new scssphp repository and monitoring it. Will provide an update with the next bp release, that's coming before 10.x. Thanks for making me aware of this.

**Comment by benjaminkott** [comment]
@TrueType dependecy is now defined and i switched to the new namespace.
