### ISSUE TITLE
Classes for figure and figcaption

### ISSUE THREAD

**Issue by SventB** [benjaminkott/bootstrap_package#726]
I hope I don't annoy you with all the small issues I report :-/
If so, just close this ticket ;)

There's one more:
Bootstrap proposes this structure of images (see https://getbootstrap.com/docs/4.3/content/figures/):

```
<figure class="figure">
  <img src="..." class="figure-img img-fluid" alt="...">
  <figcaption class="figure-caption">A caption for the above image.</figcaption>
</figure>
```

Your structure is slightly different ;)

**Comment by benjaminkott** [comment]
@SventB its refreshing to have small issues - because they are usually easy to fix and your descriptions are really good. so keep it up! 

Some changes are actually intended, since i still need to support bootstrap 3 for the next cycle, and bootstrap 4 is moving to a utility css approach in multiple areas. This is actually a big problem, since it makes theming almost impossible. 

I am trying to find a middleground here, to touch the templates as less as possible - because all template changes will lead to breaking changes to someone that customized parts of the bootstrap package. I´ve done this mistake in the past and really try to avoid it in further versions. 

Currently i tend to introduce new components that react to all bootstrap variable changes to be compatible, but trying to avoid their markup styling, except i really agree with them and think i can support that for years to come. So users have a more easy upgrade path, even if their customizings are quite complex - this also means the markup needs to be prepared for that so to be sorted around, restyled etc.

I hope you can follow my decisions here.

**Comment by benjaminkott** [comment]
I am closing this issue since i dot now plan to move to bootstrap 4 markup for image rendering for now.

**Comment by benjaminkott** [comment]
@SventB please continue to open issues if you have questions or remarks.

**Comment by SventB** [comment]
@benjaminkott I will, and thank you for clarifying the reason for this.

But why do you need to support Bootstrap 3? Bootstrap 4 was released 1,5 years ago and development on Bootstrap 3 has been stopped in 2016 (https://github.com/twbs/bootstrap/issues/20631)

**Comment by benjaminkott** [comment]
@SventB the usecase depends what role do you take - i want to help people to migrate their website to bootstrap 4 - for this they need to have a compatible version of available so they can upgrade their existing site so for example 9.5 or 10.x and then make the switch for bp4 in a separate step.

Bootstrap 5 is already in development, and also people using the bp currently with bootstrap 4 need an upgrade path to 5, so i will probably try to find a middle ground here again, and support bs4 and bp5 at the same time.

**Comment by SventB** [comment]
@benjaminkott Perhaps you want to add the Bootstrap classes now to images? Bootstrap 4 and 5 are using the same classes now.
