### ISSUE TITLE
Where to turn off server side scss compilation

### ISSUE THREAD

**Issue by hilburger** [benjaminkott/bootstrap_package#733]
# Support

Hi Benjamin! 

Love to work with your package. 
Now I have a heavy load problem on one server due to css-compilation. 
Where can I turn it off as I need to compile it locally and upload the final css file?

Best regards, 
Tom

**Comment by benjaminkott** [comment]
@hilburger all bp versions assign their scss/less through typoscript. its unified to 

Example:
```
page.includeCSS.theme = EXT:bootstrap_package/Resources/Public/Scss/Theme/theme.scss
```

You can just overwrite that one with your CSS file in TypoScript Setup.
I guess you're running a version < BP 10?

**Comment by hilburger** [comment]
Thanks a lot. Yes it's a 8.7 LTS

**Comment by benjaminkott** [comment]
@hilburger it`s https://packagist.org/packages/scssphp/scssphp for the on demand rendering, it`s also shipped as composer dependency since v11. 

But we also ship a compiled version you can see the whole build configuration here:
https://github.com/benjaminkott/bootstrap_package/blob/master/Build/package.json
https://github.com/benjaminkott/bootstrap_package/blob/master/Build/Gruntfile.js

**Comment by gilbertsoft** [comment]
@hilburger Hey Tom, is your question answered and can we close this issue?

**Comment by hilburger** [comment]
Hi @gilbertsoft!
Sorry for the delay on this. 
Had no time to figure that out but decided instead to stick to the restriction of standard Sass-handling. 
Thanks again for the information - will try to compare the versions Benjamin mentioned on a rainy week-end :-)
