### ISSUE TITLE
Meta navigation in header and footer

### ISSUE THREAD

**Issue by SventB** [benjaminkott/bootstrap_package#75]
Most webpages contain a meta navigation in header and/or footer. And therefore this navigations should be preconfigured in your introduction package.

I've prepared a solution in my fork, there are two sysfolder pages and the editor can add pages there (preferred page type "shortcut"):
![screen](https://cloud.githubusercontent.com/assets/2690489/4859352/3b667f54-60e9-11e4-9740-321dab76cb52.png)

These pages are outputted with menu type "directory".

Do you wish to merge this with your package?

**Comment by benjaminkott** [comment]
Support for meta menus has been added a while ago, the default position is in the footer. Please see:
https://github.com/benjaminkott/bootstrap_package/commit/66c76500995f76b50aabe577f8e2d7685dd8be7d

I am currently not planning to also add this to the header section since bootstrap itself does not have a suggested implementation for that and i do not wand too much custom markup in that area.
