### ISSUE TITLE
Discussion about replacing hammer.js

### ISSUE THREAD

**Issue by MartinHotmann** [benjaminkott/bootstrap_package#856]
# Support

## Description
I just set up BootstrapPackage on TYPO3 v10 and added a sitepackage to delete ressources I dont need to make it as slim as possible.
I also unloaded hammer.js and did not notice any FCE that is nopt working. Might I ask what hammer.js was for?

Why I want to remove it?

it was in v2.0.7 (v2.0.8 already released) and last release was back in 2016. What is very old for a JS library.
Anyway I dont think its needed anymore. Thats why I ask for what it was implemented?
I always try to just include as less ressources as possible but as much as needed.

As long as cgi-structuredcontent-rendering is not working/implemented in TYPO3 excluding everything what is not needed is very crucial as every JS and CSS every included is getting loaded at every page/site.

**Comment by gilbertsoft** [comment]
It's used for the carousel swipe to detect touch gestures see https://github.com/benjaminkott/bootstrap_package/blob/master/Resources/Public/JavaScript/Src/bootstrap.swipe.js#L8

I'm not sure if it's still needed or nowadays already implemented with TWB. @benjaminkott ?

**Comment by MartinH0** [comment]
True, I did not notice it as I used the Carousel with just one page back in the days. Now I dont use it anymore.

If its needed it should stay. If it can be realised with already existing Librarys it would be nice if it would

**Comment by benjaminkott** [comment]
Was the most reliable back then if we find a better one we can replace it for sure 👍

Holen Sie sich Outlook für Android<https://aka.ms/ghei36>

________________________________

**Comment by MartinH0** [comment]
Ok just had a search and wanted to mention this:

- **pureCSS Slider** ([LINK](https://cssslider.com)) (very lightweight and pureCSS as long as no touche/Swipe have to be included)
For Swipe there is a 1,6kb big JS needed.
- or **Bootstrap Slider** ([LINK](https://mobirise.com/bootstrap-carousel/))

or at least the function to exklude hammer.js if just one slide is included so the JS part (hammer.js) will not be loaded, because with one slide in your slider you cant swipe anyway and this would make hammer.js unnecessary

**Comment by gilbertsoft** [comment]
If you don't mind I like to keep this one open to give your proposition a chance....

**Comment by GuillaumeGBzh** [comment]
Or https://glidejs.com/ ? jQuery is not required.

**Comment by MartinH0** [comment]
> If you don't mind I like to keep this one open to give your proposition a chance....

@gilbertsoft Just wanted to close it as the question was "For what is hammer.js needed?" and as the question was answered and hammer.js does have its usecase I wanted to close it for not bloating the Issue section with unnecessary issues.

But thanks for giving it a chance!

> Or https://glidejs.com/ ? jQuery is not required.

Thanks for your reply and suggestion but the intention for this Issue is to:
- prevent Renderblocking
- minimizing the size of needed assets
- making the extension more lightweight and performing better out of box without breaking any features

So I was in particular looking for a pure CSS Slider.

Downside: no touch events, but you can add them with a 1.2kb big/smal js file.

So if a whole JS library should be included I would go for jQuery or for no library at all as Bootstrap itself is based on jQuery itself already and adding other librarys would just add code for the same function.

So I would rather think about these steps:

- is jQuery itself needed in particular or is jQuery-slim enough for all features the bootstrap_package offers?

Difference between them:
[jquery-3.4.1.min.js](https://code.jquery.com/jquery-3.4.1.min.js): 86.1kb (30.4kb gzip)
[jquery-3.4.1.slim.min.js](https://code.jquery.com/jquery-3.4.1.slim.min.js): 69.4kb (24.3kb gzip)

So effective its 20% smaller and is optimitzed to be much more lightweight and produce less renderblocking, so its perfect for mobile optimization IF bootstrap_package does not offer features which are not working with it.

I personally think including just another JS Library on top is not a good option.

**Comment by gilbertsoft** [comment]
Is removed now see https://github.com/benjaminkott/bootstrap_package/commit/357bc410025604825161f29f8251a3c197619192
