### ISSUE TITLE
flexform values of small and fullscreen carousel do not reach frontend 

### ISSUE THREAD

**Issue by mediaessenz** [benjaminkott/bootstrap_package#859]
# Bug Report

## Description

The flexform values "interval", "transition", "wrap" and "show_nav_title" of small and fullscreen carousel do not reach frontend. For carousel it works.

## Steps to Reproduce

1. Add a content element of type small carousel
2. Add some items of type background images
3. Set transition to fade and check wrap
4. Open page with content in frontend

### Expected behavior

A small carousel with changing images with a fade effect, which starts from the beginning after reaching there last image

### Actual behavior

A small sider who changes images with a slide effect, which stops when reaching last image

## Versions

TYPO3 9.5.14
bootstrap_package 11.0.2

**Comment by Moongazer** [comment]
I can confirm the issue for **all** content-elements which using FlexForm configuration. It seems somehow the `pi_flexform` field is "pre-processed" when it reaches the FlexFormProcessor. The `process()` function returns in line 70 because `$processedData['data'][$fieldName]` contains an array filled with the "raw flexform" structure (like data => sDEF => lDEF => ... etc), but being a string is expected.

TYPO3 10.4.12
bootstrap_package 11.0.2

**Comment by benjaminkott** [comment]
does not seem to exist on master and 13
