### ISSUE TITLE
Gallery not compatible with TYPO3 v10 

### ISSUE THREAD

**Issue by dahaupt** [benjaminkott/bootstrap_package#887]
# Bug Report

## Prerequisites

* [ ] Can you reproduce the problem on TYPO3 v8.7 LTS
* [ ] Can you reproduce the problem on TYPO3 v9.5 LTS
* [x] Can you reproduce the problem on TYPO3 v10.4 LTS
* [x] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3Abenjaminkott+repo%3Abenjaminkott%2Fbootstrap_package)
  to see if your bug or enhancement is already reported?

## Description

The content element 'Gallery' does not work anymore after upgrading TYPO3 to v10.4 LTS.

## Steps to Reproduce

1. Add a content element of type 'Gallery'
2. Open page in frontend

### Actual behavior

Error message:
```
(1/1) #1540246570 TYPO3Fluid\Fluid\Core\ViewHelper\Exception
No Content Object definition found at TypoScript object path "tt_content.gallery.20"
```

## Versions

TYPO3 v10.4.2
bootstrap_package: master#6cded41

**Comment by dahaupt** [comment]
I think I found a solution. I will create a PR soon.

**Comment by benjaminkott** [comment]
@dahaupt @gilbertsoft will check with @alexanderschnitzler later

**Comment by alexanderschnitzler** [comment]
Short information here:
https://github.com/TYPO3/TYPO3.CMS/commit/3bddf0968f758711847be5a39d1aeaee792c3bd5#diff-cbcaffb01d80e0e3d11dcce528646e31R189

This change causes Fluid to actually use the defined action name generic which then tries to render the `Generic.html` instead of the `Gallery.html`. I talked to Benji and when changing the `controllerActionName` to `gallery`, everything works fine in 10 and it should as well in 9.
