### ISSUE TITLE
Typo3 v10.4.9 - speaking URLs not not working

### ISSUE THREAD

**Issue by MVolontar** [benjaminkott/bootstrap_package#972]
# Support

## Description
I installed TYPO3 v10.4.9 with boostrap package and created a few custom pages to try things out. I noticed that the "speaking URLs" are not working and I have no idea why. Note that I am a total bigginer in TYPO3, so I'm probably missing something obvious.

Example:
We have a page called Photos. The URL created by "URL Segment" in Page module > "Edit page properties" is https://example.com/photos and the ID of the page is 84.

If I click on the view icon in the Page module, URL https://example.com/photos opens in the frontend and I get a message that says "Not Found - The requested URL was not found on this server".

On the other hand, if I type URL with ID in the browser manually, like so: https://example.com/index.php?id=84, it works perfectly fine. This problem is present for every page I create.

I have created site configuration. Below is the content of config.yaml:

    base: 'https://example.com'
    baseVariants: {  }
    errorHandling: {  }
    languages:

        title: 'Example Site'
        enabled: true
        base: 'https://example.com/'
        typo3Language: default
        locale: en_US.UTF-8
        iso-639-1: en
        websiteTitle: ''
        navigationTitle: English
        hreflang: en-US
        direction: ''
        flag: us
        languageId: '0'
    rootPageId: 1
    routes: {  }
    websiteTitle: ''

Please help. What am I missing here?
If I should paste some more data to help resolve the problem, please let me know. Thank you in advance.

**Comment by gilbertsoft** [comment]
Hi @MVolontar 

Your problem is not related to the Bootstrap Package but to TYPO3. I suggest you to use Slack (see my.typo3.org) or ask at StackOverflow.

One thing which looks wrong is the `base` of the language, this should be just a `/`. There are so many things which can go wrong here e.g. like the webserver configuration.

Slack is probably the best choice for this question. Let me know if you need support for your registration or connecting your TYPO3 account to Slack, just add a comment bellow.

Regards
Simon
