### ISSUE TITLE
Question: Cross-Site Scripting in Content Rendering

### ISSUE THREAD

**Issue by olivermeckel** [benjaminkott/bootstrap_package#996]
We have received your notification about the security vulnerability and have fixed it with an update to the latest release. Many thanks for the quick closure of the security gap.

In the Bootstrap Package you also use the f:format.raw in some cases. Is there any need to worry about cross-site scripting when using this viewhelper?

In some projects we override the headline-partials using f:format.raw to manually add line breaks (the editor can add the br-Tag) and the output creates an HTML-Tag. Not the smartest solution, but it works. ;-)

**Comment by ohader** [comment]
That's a good question, but I think it should be moved to another place since it concerns templating with Fluid in general, not only the `bootstrap_package`.

→ I've create an issue at https://github.com/TYPO3-Documentation/TYPO3CMS-Tutorial-Templating/issues/39, please let's continue there

There has been a short discussion on Twitter recently, which gives some insights into prevention techniques - see https://twitter.com/infabo/status/1387015932392902656. In anyway, I totally agree there should be good documentation on how to use the Fluid templating engine correctly and secure.
